///<reference types='cypress'/>

describe('US-012 Funcionalidade de membros', () => {
  it('Deve validar cadastro com sucesso', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-firstname").type("Diego")
    cy.get("#signup-lastname").type("Pereira")
    cy.get("#signup-email").type("diego@testes4.com")
    cy.get("#signup-phone").type("000000000000")
    cy.get("#signup-password").type("Teste&2024")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should ('contain', 'Cadastro realizado com sucesso' )
  })

  it('Deve validar mensagem de erro com e-mail duplicado', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-firstname").type("Diego")
    cy.get("#signup-lastname").type("Pereira")
    cy.get("#signup-email").type("diego@testes5.com")
    cy.get("#signup-phone").type("14956234578")
    cy.get("#signup-password").type("Teste&2024")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should('to contain' , 'Este email já está cadastrado')
  })

  it('Deve validar mensagem cadastro sem o campo de telefone preenchido', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-firstname").type("Diego")
    cy.get("#signup-lastname").type("Pereira")
    cy.get("#signup-email").type("diego@testes6.com")
    cy.get("#signup-password").type("Teste&2024")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should ('contain' , 'Cadastro realizado com sucesso')
  })

  it('Deve validar mensagem de erro por campo Nome nao preenchido', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-lastname").type("Pereira")
    cy.get("#signup-email").type("d_teste1@teste.com")
    cy.get("#signup-password").type("Teste&2024")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should ('contain', "Nome não pode estar vazio")
  })

  it('Deve validar mensagem de erro por campo Sobrenome nao preenchido', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-firstname").type("Diego")
    cy.get("#signup-email").type("d_teste2@teste.com")
    cy.get("#signup-password").type("Teste&2024")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should ('contain', "Sobrenome não pode estar vazio")
  })
  it('Deve validar mensagem de erro por campo email nao preenchido', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-firstname").type("Diego")
    cy.get("#signup-lastname").type("Pereira")
    cy.get("#signup-password").type("Teste&2024")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should ('contain', "Email não pode estar vazio")
  })
  it('Deve validar mensagem de erro por campo senha nao preenchido', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-firstname").type("Diego")
    cy.get("#signup-lastname").type("Pereira")
    cy.get("#signup-email").type("d_teste3@teste.com")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should ('contain', "Senha não pode estar vazia")
  })
  it('Deve validar mensagem de erro de senha fraca', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-firstname").type("Diego")
    cy.get("#signup-lastname").type("Pereira")
    cy.get("#signup-email").type("d_teste4@teste.com")
    cy.get("#signup-password").type("072024")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should ('contain', "Senha deve ter pelo menos 8 caracteres, incluir uma letra maiúscula, um número e um caractere especial (!@#$&*)")
  })
  it('Deve validar mensagem de erro por formato de email invalido', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-firstname").type("Diego")
    cy.get("#signup-lastname").type("Pereira")
    cy.get("#signup-email").type("d_teste0.com")
    cy.get("#signup-password").type("Teste&2024")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should ('contain', "E-mail deve ser um email válido")
  })
  it('Deve validar mensagem de erro inserir no campo Nome dados inválidos', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-firstname").type("123456")
    cy.get("#signup-lastname").type("Pereira")
    cy.get("#signup-email").type("d_teste0@teste.com")
    cy.get("#signup-password").type("Teste&2024")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should ('contain', "Nome deve conter apenas caracteres alfabéticos, acentuados e espaços")
  })
  it('Deve validar mensagem de erro inserir no campo Nome dados inválidos', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-firstname").type("123456")
    cy.get("#signup-lastname").type("Pereira")
    cy.get("#signup-email").type("d_teste4@teste.com")
    cy.get("#signup-password").type("Teste&2024")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should ('contain', "Nome deve conter apenas caracteres alfabéticos, acentuados e espaços")
  })
  it('Deve validar mensagem de erro inserir no campo Sobrenome dados inválidos', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#signup-firstname").type("Diego")
    cy.get("#signup-lastname").type("123456$")
    cy.get("#signup-email").type("d_teste5@teste.com")
    cy.get("#signup-password").type("Teste&2024")
    cy.get("#signup-button").click()
    cy.get('#signup-response').should ('contain', "Sobrenome deve conter apenas caracteres alfabéticos, acentuados e espaços")
  })

  it('Deve validar o link de politca da privacidade', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get('a').click()
    cy.contains("Politica de Privacidade")
    cy.url().should('include', '/polices.html')
    cy.get('#results-section').should ("be.visible")
  })
  
  it('Deve validar a busca de filme', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#search-input").type("Matrix")
    cy.get("#search-button").click()
    cy.get('#results-section > :nth-child(1) > p')
    cy.get('#results-section > :nth-child(1) > img')
    cy.get('#results-section > :nth-child(1) > p')
    cy.get('#results-section > :nth-child(1) > img')
  })

  it('Deve validar a limpeza do campo busca de filme', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#clear-button").click()
    cy.get('#search-input').should("have.value" , "")
    cy.get('#results-section').should("be empty")
  })
  it.only('Deve validar a busca com o campo vazio', () => {
    cy.visit('http://127.0.0.1:8080/')
    cy.get("#search-button").click()  
    cy.get('#results-section').should("contain", "Por favor, digite o nome de um filme")
  })
    it('Deve validar a busca de filme invalido ou não encontrado.', () => {
      cy.visit('http://127.0.0.1:8080/')
      cy.get("#search-input").type("O Poderoso Chefao")
      cy.get("#search-button").click()
      cy.get('#results-section').should("contain", "Filme não encontrado.")
    })  
   
})
